##===- Break/lib/Strator/Makefile -----------------*- Makefile -*-===##

LEVEL=../..

LIBRARYNAME = Strator
BUILD_ARCHIVE = 1
LOADABLE_MODULE = 1
# USEDLIBS = LLVMLocalIdentifier.a LLVMUseDefBuilder.a
# LLVMMultithreadFinder.a


include $(LEVEL)/Makefile.common